apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: istio-3scale
spec:
  tracing:
    sampling: 10000
    type: Jaeger
  policy:
    mixer:
      enableChecks: true
    type: Mixer
  addons:
    3scale:
      enabled: true
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  version: v2.0
  telemetry:
    type: Mixer