apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: >-
      APIManager.v1alpha1.apps.3scale.net,APIManagerBackup.v1alpha1.apps.3scale.net,APIManagerRestore.v1alpha1.apps.3scale.net,Backend.v1beta1.capabilities.3scale.net,Product.v1beta1.capabilities.3scale.net,Tenant.v1alpha1.capabilities.3scale.net
  name: 3scale-og
spec:
  targetNamespaces:
    - 3scale