apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 3scale

resources:
  - 3scale-namespace.yaml
  - 3scale-operatorgroup.yaml
  - 3scale-subscription.yaml
  - 3scale-objectbucketclaim.yaml