apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"bookstoredb"}]'
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/pittar-sandbox/fuse7-lab-openapi-to-java
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: bookstore
    app.kubernetes.io/component: bookstore
    app.kubernetes.io/instance: bookstore
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: bookstore-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-8-ubi8
  name: bookstore
  namespace: bookstore
spec:
  clusterIP: 172.30.196.236
  clusterIPs:
  - 172.30.196.236
  ports:
  - appProtocol: http
    name: 8080-tcp
    port: 8080
  - appProtocol: https
    name: 8443-tcp
    port: 8443
  - name: 8778-tcp
    port: 8778
  selector:
    app: bookstore
    deploymentconfig: bookstore
