apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bookstore-istio
spec:
  gateways:
    - istio-gateway/default-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /camel
      route:
        - destination:
            host: bookstore
            port:
              number: 8080